# Generated by Django 4.2.16 on 2024-12-11 16:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('destination_name', models.CharField(max_length=255, unique=True)),
                ('pin_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Pin code must be a 6-digit number.', regex='^\\d{6}$')])),
                ('kilometer', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('flag', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='branches.branchmaster')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='destination_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Destination Master',
                'verbose_name_plural': 'Destination Masters',
                'db_table': 'destination_master',
            },
        ),
    ]
