# Generated by Django 4.2.16 on 2024-12-11 16:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import parties.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('flag', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='party_type_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_type_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Party Type',
                'verbose_name_plural': 'Party Types',
                'db_table': 'party_types',
            },
        ),
        migrations.CreateModel(
            name='PartyMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('party_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_no', models.TextField()),
                ('email_id', models.TextField()),
                ('gst_no', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Pincode must be a 6-digit number.', regex='^\\d{6}$')])),
                ('credit_period', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)])),
                ('credit_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('po_no', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='PO number must contain only digits.', regex='^\\d+$')])),
                ('vendor_code', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Vendor code must contain only digits.', regex='^\\d+$')])),
                ('quotation_number', models.CharField(blank=True, max_length=50, null=True)),
                ('party_weekly_off', models.CharField(blank=True, help_text="Enter valid days of the week (e.g., 'Monday, Tuesday').", max_length=100, validators=[parties.models.validate_weekly_off_days])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('flag', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='destinations.destinationmaster')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='branches.branchmaster')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='party_created_by', to=settings.AUTH_USER_MODEL)),
                ('party_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parties', to='parties.partytypes')),
                ('pay_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_master_pay_type', to='transactions.paytypes')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Party Master',
                'verbose_name_plural': 'Party Masters',
                'db_table': 'party_master',
            },
        ),
    ]
