# Generated by Django 4.2.16 on 2024-12-11 16:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_no', models.TextField()),
                ('email_id', models.TextField(blank=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('IFSC_code', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Invalid IFSC code format.', regex='^[A-Za-z]{4}[a-zA-Z0-9]{7}$')])),
                ('account_no', models.CharField(blank=True, max_length=20)),
                ('UPI_id', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.EmailValidator])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('flag', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='owner_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Owner Master',
                'verbose_name_plural': 'Owner Masters',
                'db_table': 'owner_master',
            },
        ),
        migrations.CreateModel(
            name='VendorTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('flag', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='vendor_type_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_type_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Types',
                'verbose_name_plural': 'Vendor Types',
                'db_table': 'vendor_types',
            },
        ),
        migrations.CreateModel(
            name='VehicalTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('flag', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='vehical_type_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehical_type_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehical Types',
                'verbose_name_plural': 'Vehical Types',
                'db_table': 'vehical_types',
            },
        ),
        migrations.CreateModel(
            name='VehicalMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vehical_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Vehical number must be alphanumeric and uppercase.', regex='^[A-Z0-9-]+$')])),
                ('chassis_number', models.CharField(default='DEFAULTCHASSIS123', max_length=20, validators=[django.core.validators.RegexValidator(message='Chassis number must be alphanumeric and uppercase.', regex='^[A-Z0-9]+$')])),
                ('rc_book', models.ImageField(blank=True, null=True, upload_to='RC_book/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('flag', models.BooleanField(default=True)),
                ('total_km',models.PositiveIntegerField(default=0, help_text='Total kilometers traveled')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='vehical_created_by', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicals', to='vehicals.ownermaster')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehical_updated_by', to=settings.AUTH_USER_MODEL)),
                ('vehical_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicals', to='vehicals.vehicaltypes')),
                ('vendor_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehicals', to='vehicals.vendortypes')),
            ],
            options={
                'verbose_name': 'Vehical Master',
                'verbose_name_plural': 'Vehical Masters',
                'db_table': 'vehical_master',
            },
        ),
        migrations.CreateModel(
            name='DriverMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_no', models.TextField()),
                ('address', models.TextField(blank=True, null=True)),
                ('license_no', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('license_exp_date', models.DateField(blank=True, null=True)),
                ('aadhar_no', models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Aadhar number must be a 12-digit number.', regex='^\\d{12}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('flag', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='driver_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver Master',
                'verbose_name_plural': 'Driver Masters',
                'db_table': 'driver_master',
            },
        ),
    ]
