# Generated by Django 4.2.16 on 2024-12-11 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteStations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('km', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('flag', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='route_stations_created_by', to=settings.AUTH_USER_MODEL)),
                ('route_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_stations_branch', to='branches.branchmaster')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_stations_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'route_stations',
            },
        ),
        migrations.CreateModel(
            name='RouteMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('flag', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='route_master_created_by', to=settings.AUTH_USER_MODEL)),
                ('from_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_stations_from_branch', to='branches.branchmaster')),
                ('route_stations', models.ManyToManyField(blank=True, related_name='route_master_stations', to='routes.routestations')),
                ('to_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_stations_to_branch', to='branches.branchmaster')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_master_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'route_master',
            },
        ),
        migrations.CreateModel(
            name='SlapMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('up_km', models.IntegerField(default=0)),
                ('to_km', models.IntegerField(default=0)),
                ('no_day', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('flag', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='slap_master_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slap_master_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'slap_master',
            },
        ),
    ]
