"""
Django settings for transport_system project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path
from django.conf import settings
from django.templatetags.static import static
import pymysql



pymysql.version_info =(1,4,6,'final',0)
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f999sj890cs0*%53)6mx491tv#dmja(q_9oo_op4s#_vtz0-)3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "admin_interface",
    "colorfield",
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'users',
    'company',
    'account',
    'branches',
    'destinations',
    'parties',
    'routes',
    'vehicals',
    'items',
    'accounts',
    'transactions',
    'lr_booking',
    'collection',
    'delivery',
    'history',
    

]

MIDDLEWARE = [
    'django.middleware.locale.LocaleMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'transport_system.middleware.RedirectAdminLoginMiddleware',
    'transport_system.middleware.RefreshSlidingTokenMiddleware',
  
]

# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:4200",
#     "http://103.235.106.107:50000",
#     "http://103.190.54.140:50000",
# ]

CORS_ALLOW_ALL_ORIGINS = True

CORS_EXPOSE_HEADERS = ['Authorization']

CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'transport_system.urls'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/home/'



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'debug': True,
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'transport_system.context_processors.financial_year_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'transport_system.wsgi.application'


# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),   
    # 'COERCE_DECIMAL_TO_STRING': False,
}

# Simple JWT Configuration (optional: adjust as needed)

# SIMPLE_JWT = {
#     'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # Adjust token lifetime
#     'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
#     'ROTATE_REFRESH_TOKENS': True,
#     'BLACKLIST_AFTER_ROTATION': True,
   
# }

SIMPLE_JWT = {
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.SlidingToken',),
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=60),  # Expire after 5 minutes of inactivity
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),  # Maximum lifetime for active sessions is 1 day
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Email backend

# Gmail settings
# it's testing code present inside vahical app view file
EMAIL_HOST = 'smtp.gmail.com'  
EMAIL_PORT = 587 
EMAIL_USE_TLS = True 
# EMAIL_HOST_USER = 'quivonexsolutions@gmail.com' 
# EMAIL_HOST_PASSWORD = 'ctbc hzwl qvrs ajek'
EMAIL_HOST_USER = 'jkroadways1987@gmail.com' 
EMAIL_HOST_PASSWORD = 'wakf ygsm kbox zpjd'
# EMAIL_HOST_USER = 'rhachhad@gmail.com' 
# EMAIL_HOST_PASSWORD = 'yjnf vxxx zziy tinh'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
# db_transport hiox
# transport_db aws
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'transport_db',
        'HOST': 'localhost',
        'PORT': '3306',
        'USER': 'root',
        'PASSWORD': 'KScp*g{ic]6aYa8%',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators


# AUTH_USER_MODEL = 'users.CustomUser'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



def media_absolute_url(request):
    return {
        'MEDIA_URL': request.build_absolute_uri(settings.MEDIA_URL),
    }

TEMPLATES[0]['OPTIONS']['context_processors'].append('transport_system.context_processors.media_absolute_url')